### ISSUE TITLE
About argoverse

### ISSUE THREAD

**Issue by Zbozhou** [vita-epfl/UniTraj#1]
Thanks for your work, I am wondering how to use argoverse data to train.

**Comment by Alan-LanFeng** [comment]
Hi, I just updated the av2 documentation in scenarionet: https://scenarionet.readthedocs.io/en/latest/argoverse2.html.

Please refer to the documentation to get av2 data

**Comment by 33zzstar** [comment]
May I ask if only the motion forecasting section of the data needs to be downloaded, or if all data (sensor, lidar, motion forecasting, or tbv.) needs to be downloaded

**Comment by Alan-LanFeng** [comment]
Hi, only the motion forecasting data need to be downloaded.

**Comment by 33zzstar** [comment]
Thank you for your timely recovery

**Comment by 33zzstar** [comment]
Thank you for your prompt reply
