### ISSUE TITLE
how to generate intention points file for nuscenes?

### ISSUE THREAD

**Issue by turboxin** [vita-epfl/UniTraj#13]
Hi @Alan-LanFeng , thanks for open sourcing this great work!

I'm wondering how to generate intention points file for nuscenes dataset?

I noticed in initial commit there is a intention points file for nuscenes ([unitraj/models/mtr/cluster_64_center_dict_6s.pkl](https://github.com/vita-epfl/UniTraj/commit/7974f95f882bb19fc7b1567cbe4e4c420a613366#diff-7812f749a2a1a7d83cc8e30baa25e4845aca42c07c4bae5e5b1fcb4937bba4f8)) , but was deleted in later commit.

And which dataset is this intention point file(https://github.com/vita-epfl/UniTraj/blob/main/unitraj/models/mtr/cluster_64_center_dict_6s.pkl) generated from.

Looking forward to your reply, thanks a lot!

**Comment by Alan-LanFeng** [comment]
The current intention file is generated from Waymo, which is proved to have better performance comparing to nuscenes intention point. So I removed the nuscenes intention point.

You can generate new intention points with k_means.py in the repo
