### ISSUE TITLE
Question about transform trajectories to center coordiantes

### ISSUE THREAD

**Issue by ChengkaiYang** [vita-epfl/UniTraj#16]
Dear Author:
        I have noticed the function "get_agent_data" in dataset/base_dataset.py, in function "get_agent_data", we use function "transform_trajs_to_center_coords" to get trajectories transformed according to the center object heading. I wonder if heading of last time equals to dirction of last time? Why the transformed center object's trajectory not **parallel to y axis**?I used to think we can use heading of last time to transform current center objects's trajectory **parallel to y axis**, but in some cases of AV2, it doesn't seem that.Can you show me what is the problem?
![image](https://github.com/user-attachments/assets/fb86a01a-2165-4ec7-9391-e41bac2e017e)
But in some cases, it seems current trajectory of center object is **parallel to y axis**:
![image](https://github.com/user-attachments/assets/78f52d5c-729f-43a7-af6e-cf3fa9c4f054)
Here is the function to transform trajectory of center object:
![image](https://github.com/user-attachments/assets/8dc72063-8aa4-4ac3-afb6-ee0389abd2b3)
![image](https://github.com/user-attachments/assets/05fc3d30-4191-4b31-b525-0aadbfaf4b99)
![image](https://github.com/user-attachments/assets/b65a3038-85e7-4897-9a9d-614f56c32122)
Looking forward to your reply, thanks!

**Comment by Alan-LanFeng** [comment]
You can scale the plot so that x axis and y axis have the same ratio. The transformation is based on the heading so it's normal.
