### ISSUE TITLE
Question on prediction output trajectory format

### ISSUE THREAD

**Issue by tjyuyao** [vita-epfl/UniTraj#22]
I find the comment in the models to specify the output trajectory format:

```py
"""
    pred_obs: shape [c, T, B, 5] c trajectories for the ego agents with every point being the params of
                                        Bivariate Gaussian distribution.
"""
```

But it is still ambiguous to me "the params of Bivariate Gaussian distribution", 
which might refers to one of the following:

- `[x, y, sigma_x, sigma_y, rho]` where sigmas are the standard deviation and rho is the correlation coefficient.
- `[x, y, var_x, var_y, rho * sqrt(var_x * var_y)]` where the last 3 values are direct members of the covariance matrix.

Please help make clear this format, and I think it might be even better to document this in README.md.

I also have two related questions:

- Is this format mandatory, e.g. for the evaluation scripts to work consistently ?
- In which coordinate system are the predicted x and y supposed to be in ?
- In which coordinate system are the input_dict members (e.g. 'obj_trajs' and 'obj_trajs_future_state') in?

Thanks for your attention very much!

**Comment by Alan-LanFeng** [comment]
I'm also not sure about the autobot's output format. Maybe you can find it out in autobot's repo.

For your additional questions:
1. ensure your output is [c, T, B, 2], where the last dimension refers to x and y
2. The coordinate system is normalized so that the heading of an object at the current time step is the Positive x-axis direction

**Comment by tjyuyao** [comment]
OK, I got it. The output is only needed to have 5 output when specific model requires it, but UniTraj only use x and y for evaluation. And also thank you for your confirmation on the coordinate system.
