### ISSUE TITLE
Map Processing for Argoverse 2

### ISSUE THREAD

**Issue by tjyuyao** [vita-epfl/UniTraj#24]
Hello, 

I draw the `scenario['map_features']` on different plots based on the types of the map elements, according to the attached plot:

1. The drivable area boundaries are mixed with road lines. (left top)
2. Some important lanes are tagged as UNKNOWN_LINE (middle bottom), and in `BaseModel.preprocess()`, polylines with type of UNKNOWN_LINE(0) are not appended to `map_infos`, thus not fed to the network.

In your opinion, are these conclusions correct? Can you suggest me on how to fix them? Thanks a lot!

![output](https://github.com/user-attachments/assets/05602318-5b62-4516-b39e-6b9fb22e6bcc)

**Comment by Alan-LanFeng** [comment]
Hi,
for (1), it is normal. Since metadrive has unified all road boundaries as solid_singlle_white, we use it to represent the road boundary for all three datasets.

for (2), the unknown_lines is a type called 'lane_marking' in av2. each center lane has left lane marking and right lane marking. You can manually set it to 'broken_single_white' or 'solid_single_white' if you think it's necessary

**Comment by ChengkaiYang** [comment]
> Hi, for (1), it is normal. Since metadrive has unified all road boundaries as solid_singlle_white, we use it to represent the road boundary for all three datasets.
> 
> for (2), the unknown_lines is a type called 'lane_marking' in av2. each center lane has left lane marking and right lane marking. You can manually set it to 'broken_single_white' or 'solid_single_white' if you think it's necessary

Sorry to disturb you. Could you please tell me how to add lane_unknown?
In type.py ,add row 24
![image](https://github.com/user-attachments/assets/758c0cc8-f679-47a6-9820-44b6339a4923)
In base_dataset.py add index 0 to row 257
![image](https://github.com/user-attachments/assets/48a227db-bab4-449f-9afa-630461c0a88e)
Does this correct?

**Comment by Alan-LanFeng** [comment]
Hi, unknown line is assigned to 0 by default. You do not need to add row 24 in type.py
