### ISSUE TITLE
Training Issue

### ISSUE THREAD

**Issue by sandipsharan** [vita-epfl/UniTraj#26]
Hello, 

I was trying to make sure UniTraj installation works properly. I followed all the steps mentioned in the readme.MD file. But when running python train method=autobot. It shows some error. The error log is given below. I running this currently in Windows.  Can you provide some feedback on how to resolve this issue

PS D:\x\x\UniTraj\unitraj> python train.py method=autobot                                                                                                                                       
C:\Users\Asus\anaconda3\envs\scenarionet\lib\site-packages\hydra\_internal\defaults_list.py:251: UserWarning: In 'config': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
Global seed set to 42
Loading training data...
DATA USAGE THIS DATASET:  125
Warning: cache path data_samples/nuscenes\cache_autobot already exists, skip
CACHE PATH:  data_samples/nuscenes\cache_autobot
Error executing job with overrides: ['method=autobot']
Traceback (most recent call last):
  File "D:\x\x\UniTraj\unitraj\train.py", line 23, in train
    train_set = build_dataset(cfg)
  File "D:\x\x\UniTraj\unitraj\datasets\__init__.py", line 13, in build_dataset
    dataset = __all__[config.method.model_name](
  File "D:\x\x\UniTraj\unitraj\datasets\autobot_dataset.py", line 7, in __init__
    super().__init__(config, is_validation)
  File "D:\x\x\UniTraj\unitraj\datasets\base_dataset.py", line 36, in __init__
    self.load_data()
  File "D:\x\x\UniTraj\unitraj\datasets\base_dataset.py", line 57, in load_data
    file_list = self.get_data_list(data_usage_this_dataset)
  File "D:\x\x\UniTraj\unitraj\datasets\base_dataset.py", line 499, in get_data_list
    raise ValueError('Error: file_list.pkl not found')
ValueError: Error: file_list.pkl not found

**Comment by Alan-LanFeng** [comment]
try set overwrite_cache: True in config.yaml
