### ISSUE TITLE
Similar Wandb Bug Encountered (not able to be solved by commenting out wandb.log({"prediction": [wandb.Image(img)]})

### ISSUE THREAD

**Issue by jehrenstonemann** [vita-epfl/UniTraj#29]
After I run python train.py method=autobot, I am still getting some errors.

/home/xyz/miniconda3/envs/unitraj/lib/python3.9/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'config': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
Seed set to 42
/home/xyz/miniconda3/envs/unitraj/lib/python3.9/site-packages/torch/nn/modules/transformer.py:307: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(f"enable_nested_tensor is True, but self.use_nested_tensor is False because {why_not_sparsity_fast_path}")
Loading training data...
Using 31 processes to load data...
0/2 data processed
1/2 data processed
Loaded 248 samples from data_samples/nuscenes
Data loaded
Loading validation data...
Using 31 processes to load data...
0/2 data processed
1/2 data processed
Loaded 248 samples from data_samples/nuscenes
Data loaded
GPU available: True (cuda), used: False
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
/home/xyz/miniconda3/envs/unitraj/lib/python3.9/site-packages/pytorch_lightning/trainer/setup.py:177: GPU available but not used. You can set it by doing `Trainer(accelerator='gpu')`.
/home/xyz/miniconda3/envs/unitraj/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py:75: Starting from v1.9.0, `tensorboardX` has been removed as a dependency of the `pytorch_lightning` package, due to potential conflicts with other packages in the ML ecosystem. For this reason, `logger=True` will use `CSVLogger` as the default logger, unless the `tensorboard` or `tensorboardX` packages are found. Please `pip install lightning[extra]` or one of them to enable TensorBoard support by default
/home/xyz/miniconda3/envs/unitraj/lib/python3.9/site-packages/torch/optim/lr_scheduler.py:60: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

   | Name                   | Type               | Params  | Mode 
------------------------------------------------------------------------
0  | agents_dynamic_encoder | Sequential         | 384     | train
1  | temporal_attn_layers   | ModuleList         | 330 K   | train
2  | social_attn_layers     | ModuleList         | 330 K   | train
3  | map_encoder            | MapEncoderPts      | 100.0 K | train
4  | map_attn_layers        | MultiheadAttention | 66.0 K  | train
5  | tx_decoder             | ModuleList         | 463 K   | train
6  | pos_encoder            | PositionalEncoding | 2.7 K   | train
7  | output_model           | OutputModel        | 33.7 K  | train
8  | mode_map_attn          | MultiheadAttention | 66.0 K  | train
9  | prob_decoder           | MultiheadAttention | 66.0 K  | train
10 | prob_predictor         | Linear             | 129     | train
11 | criterion              | Criterion          | 0       | train
   | other params           | n/a                | 46.8 K  | n/a  
------------------------------------------------------------------------
1.5 M     Trainable params
2.7 K     Non-trainable params
1.5 M     Total params
6.027     Total estimated model params size (MB)
110       Modules in train mode
0         Modules in eval mode
Sanity Checking: |                                                                                                                                          | 0/? [00:00<?, ?it/s]/home/xyz/miniconda3/envs/unitraj/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=31` in the `DataLoader` to improve performance.
/home/xyz/miniconda3/envs/unitraj/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=31` in the `DataLoader` to improve performance.
/home/xyz/miniconda3/envs/unitraj/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py:298: The number of training batches (2) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.
Epoch 19: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  0.67it/s, v_num=6/home/xyz/unitraj/UniTraj/unitraj/utils/visualization.py:198: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  fig, ax = plt.subplots()
Epoch 99: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  0.51it/s, v_num=6]`Trainer.fit` stopped: `max_epochs=100` reached.                                                                                                                                  
Epoch 99: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  0.50it/s, v_num=6]
FIT Profiler Report

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|  Action                                                                                                                                                                       |  Mean duration (s)      |  Num calls            |  Total time (s)       |  Percentage %         |
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|  Total                                                                                                                                                                        |  -                      |  11811                |  368.48               |  100 %                |
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|  run_training_epoch                                                                                                                                                           |  3.6641                 |  100                  |  366.41               |  99.437               |
|  run_training_batch                                                                                                                                                           |  1.4564                 |  200                  |  291.29               |  79.05                |
|  [LightningModule]AutoBotEgo.optimizer_step                                                                                                                                   |  1.4546                 |  200                  |  290.92               |  78.951               |
|  [Strategy]SingleDeviceStrategy.backward                                                                                                                                      |  1.1731                 |  200                  |  234.62               |  63.671               |
|  [Strategy]SingleDeviceStrategy.validation_step                                                                                                                               |  0.71655                |  101                  |  72.371               |  19.64                |
|  [Strategy]SingleDeviceStrategy.training_step                                                                                                                                 |  0.27261                |  200                  |  54.522               |  14.797               |
|  [_EvaluationLoop].val_next                                                                                                                                                   |  0.015092               |  101                  |  1.5243               |  0.41367              |
|  [_TrainingEpochLoop].train_dataloader_next                                                                                                                                   |  0.0064946              |  200                  |  1.2989               |  0.35251              |
|  [Callback]ModelCheckpoint{'monitor': 'val/brier_fde', 'mode': 'min', 'every_n_train_steps': 0, 'every_n_epochs': 1, 'train_time_interval': None}.on_train_epoch_end          |  0.0088605              |  100                  |  0.88605              |  0.24046              |
|  [LightningModule]AutoBotEgo.configure_gradient_clipping                                                                                                                      |  0.0014442              |  200                  |  0.28883              |  0.078385             |
|  [LightningModule]AutoBotEgo.on_validation_model_zero_grad                                                                                                                    |  0.0012002              |  100                  |  0.12002              |  0.03257              |
|  [Strategy]SingleDeviceStrategy.batch_to_device                                                                                                                               |  0.00025674             |  301                  |  0.077279             |  0.020972             |
|  [LightningModule]AutoBotEgo.transfer_batch_to_device                                                                                                                         |  0.0002377              |  301                  |  0.071546             |  0.019417             |
|  [Callback]TQDMProgressBar.on_train_batch_end                                                                                                                                 |  0.00032351             |  200                  |  0.064701             |  0.017559             |
|  [LightningModule]AutoBotEgo.optimizer_zero_grad                                                                                                                              |  0.00017928             |  200                  |  0.035857             |  0.0097309            |
|  [Callback]TQDMProgressBar.on_validation_batch_start                                                                                                                          |  0.00020735             |  101                  |  0.020942             |  0.0056835            |
|  [LightningModule]AutoBotEgo.on_validation_model_eval                                                                                                                         |  0.00019654             |  101                  |  0.019851             |  0.0053871            |
|  [Callback]TQDMProgressBar.on_train_epoch_end                                                                                                                                 |  0.00015188             |  100                  |  0.015188             |  0.0041218            |
|  [Callback]TQDMProgressBar.on_validation_start                                                                                                                                |  0.00014777             |  101                  |  0.014925             |  0.0040504            |
|  [Callback]TQDMProgressBar.on_validation_end                                                                                                                                  |  0.0001391              |  101                  |  0.014049             |  0.0038127            |
|  [Callback]TQDMProgressBar.on_train_epoch_start                                                                                                                               |  0.00012362             |  100                  |  0.012362             |  0.0033549            |
|  [Callback]TQDMProgressBar.on_validation_batch_end                                                                                                                            |  0.00011711             |  101                  |  0.011828             |  0.0032099            |
|  [LightningModule]AutoBotEgo.on_validation_epoch_end                                                                                                                          |  4.0239e-05             |  101                  |  0.0040641            |  0.0011029            |
|  [Callback]ModelCheckpoint{'monitor': 'val/brier_fde', 'mode': 'min', 'every_n_train_steps': 0, 'every_n_epochs': 1, 'train_time_interval': None}.on_train_batch_end          |  1.4886e-05             |  200                  |  0.0029772            |  0.00080797           |
|  [Callback]ModelCheckpoint{'monitor': 'val/brier_fde', 'mode': 'min', 'every_n_train_steps': 0, 'every_n_epochs': 1, 'train_time_interval': None}.on_validation_end           |  1.5473e-05             |  101                  |  0.0015628            |  0.00042412           |
|  [LightningModule]AutoBotEgo.lr_scheduler_step                                                                                                                                |  1.5466e-05             |  100                  |  0.0015466            |  0.00041971           |
|  [Callback]ModelSummary.on_fit_start                                                                                                                                          |  0.0012219              |  1                    |  0.0012219            |  0.00033162           |
|  [Callback]TQDMProgressBar.on_after_backward                                                                                                                                  |  4.9365e-06             |  200                  |  0.0009873            |  0.00026794           |
|  [LightningModule]AutoBotEgo.configure_optimizers                                                                                                                             |  0.00063032             |  1                    |  0.00063032           |  0.00017106           |
|  [Callback]TQDMProgressBar.on_sanity_check_start                                                                                                                              |  0.00055957             |  1                    |  0.00055957           |  0.00015186           |
|  [LightningModule]AutoBotEgo.on_before_batch_transfer                                                                                                                         |  1.5725e-06             |  301                  |  0.00047334           |  0.00012846           |
|  [Callback]ModelSummary.on_train_batch_end                                                                                                                                    |  1.9758e-06             |  200                  |  0.00039516           |  0.00010724           |
|  [Callback]TQDMProgressBar.on_before_optimizer_step                                                                                                                           |  1.8569e-06             |  200                  |  0.00037138           |  0.00010079           |
|  [Callback]TQDMProgressBar.on_before_zero_grad                                                                                                                                |  1.8529e-06             |  200                  |  0.00037057           |  0.00010057           |
|  [Callback]TQDMProgressBar.on_before_backward                                                                                                                                 |  1.455e-06              |  200                  |  0.000291             |  7.8972e-05           |
|  [LightningModule]AutoBotEgo.on_after_batch_transfer                                                                                                                          |  8.5702e-07             |  301                  |  0.00025796           |  7.0007e-05           |
|  [Callback]TQDMProgressBar.on_train_batch_start                                                                                                                               |  1.2818e-06             |  200                  |  0.00025635           |  6.9571e-05           |
|  [LightningModule]AutoBotEgo.on_after_backward                                                                                                                                |  1.1622e-06             |  200                  |  0.00023244           |  6.3079e-05           |
|  [Callback]ModelSummary.on_after_backward                                                                                                                                     |  1.1621e-06             |  200                  |  0.00023242           |  6.3074e-05           |
|  [LightningModule]AutoBotEgo.on_before_zero_grad                                                                                                                              |  1.1536e-06             |  200                  |  0.00023072           |  6.2613e-05           |
|  [Callback]ModelSummary.on_before_zero_grad                                                                                                                                   |  1.1326e-06             |  200                  |  0.00022652           |  6.1473e-05           |
|  [LightningModule]AutoBotEgo.on_train_batch_end                                                                                                                               |  1.0816e-06             |  200                  |  0.00021632           |  5.8706e-05           |
|  [Callback]ModelCheckpoint{'monitor': 'val/brier_fde', 'mode': 'min', 'every_n_train_steps': 0, 'every_n_epochs': 1, 'train_time_interval': None}.on_before_backward          |  1.007e-06              |  200                  |  0.00020141           |  5.4659e-05           |
|  [Callback]ModelCheckpoint{'monitor': 'val/brier_fde', 'mode': 'min', 'every_n_train_steps': 0, 'every_n_epochs': 1, 'train_time_interval': None}.on_after_backward           |  9.9977e-07             |  200                  |  0.00019995           |  5.4264e-05           |
|  [Callback]ModelCheckpoint{'monitor': 'val/brier_fde', 'mode': 'min', 'every_n_train_steps': 0, 'every_n_epochs': 1, 'train_time_interval': None}.on_before_zero_grad         |  9.6017e-07             |  200                  |  0.00019203           |  5.2115e-05           |
|  [Callback]ModelSummary.on_before_optimizer_step                                                                                                                              |  9.0343e-07             |  200                  |  0.00018069           |  4.9035e-05           |
|  [Callback]ModelCheckpoint{'monitor': 'val/brier_fde', 'mode': 'min', 'every_n_train_steps': 0, 'every_n_epochs': 1, 'train_time_interval': None}.on_before_optimizer_step    |  8.7735e-07             |  200                  |  0.00017547           |  4.762e-05            |
|  [Callback]ModelSummary.on_validation_start                                                                                                                                   |  1.7141e-06             |  101                  |  0.00017312           |  4.6983e-05           |
|  [Callback]ModelSummary.on_validation_batch_start                                                                                                                             |  1.6366e-06             |  101                  |  0.00016529           |  4.4858e-05           |
|  [Callback]ModelSummary.on_before_backward                                                                                                                                    |  8.2147e-07             |  200                  |  0.00016429           |  4.4587e-05           |
|  [LightningModule]AutoBotEgo.on_train_batch_start                                                                                                                             |  7.6828e-07             |  200                  |  0.00015366           |  4.17e-05             |
|  [LightningModule]AutoBotEgo.on_before_backward                                                                                                                               |  6.9787e-07             |  200                  |  0.00013957           |  3.7878e-05           |
|  [Strategy]SingleDeviceStrategy.on_train_batch_start                                                                                                                          |  6.8849e-07             |  200                  |  0.0001377            |  3.7369e-05           |
|  [Callback]ModelCheckpoint{'monitor': 'val/brier_fde', 'mode': 'min', 'every_n_train_steps': 0, 'every_n_epochs': 1, 'train_time_interval': None}.on_train_batch_start        |  6.8222e-07             |  200                  |  0.00013644           |  3.7029e-05           |
|  [Callback]TQDMProgressBar.on_validation_epoch_end                                                                                                                            |  1.3491e-06             |  101                  |  0.00013626           |  3.6979e-05           |
|  [Callback]ModelSummary.on_train_batch_start                                                                                                                                  |  6.6349e-07             |  200                  |  0.0001327            |  3.6012e-05           |
|  [LightningModule]AutoBotEgo.on_before_optimizer_step                                                                                                                         |  6.5848e-07             |  200                  |  0.0001317            |  3.574e-05            |
|  [Callback]ModelSummary.on_train_epoch_start                                                                                                                                  |  1.2839e-06             |  100                  |  0.00012839           |  3.4842e-05           |
|  [Callback]ModelSummary.on_validation_batch_end                                                                                                                               |  1.2369e-06             |  101                  |  0.00012492           |  3.3902e-05           |
|  [Callback]ModelSummary.on_validation_end                                                                                                                                     |  1.2343e-06             |  101                  |  0.00012467           |  3.3833e-05           |
|  [Callback]TQDMProgressBar.on_train_end                                                                                                                                       |  0.00012413             |  1                    |  0.00012413           |  3.3688e-05           |
|  [Callback]TQDMProgressBar.on_validation_epoch_start                                                                                                                          |  1.2176e-06             |  101                  |  0.00012298           |  3.3375e-05           |
|  [Callback]ModelSummary.on_train_epoch_end                                                                                                                                    |  1.0526e-06             |  100                  |  0.00010526           |  2.8567e-05           |
|  [LightningModule]AutoBotEgo.on_validation_start                                                                                                                              |  9.6086e-07             |  101                  |  9.7047e-05           |  2.6337e-05           |
|  [Callback]TQDMProgressBar.on_train_start                                                                                                                                     |  9.3125e-05             |  1                    |  9.3125e-05           |  2.5273e-05           |
|  [Callback]ModelCheckpoint{'monitor': 'val/brier_fde', 'mode': 'min', 'every_n_train_steps': 0, 'every_n_epochs': 1, 'train_time_interval': None}.on_validation_start         |  9.2126e-07             |  101                  |  9.3047e-05           |  2.5251e-05           |
|  [Callback]ModelCheckpoint{'monitor': 'val/brier_fde', 'mode': 'min', 'every_n_train_steps': 0, 'every_n_epochs': 1, 'train_time_interval': None}.on_validation_epoch_start   |  8.7941e-07             |  101                  |  8.882e-05            |  2.4104e-05           |
|  [LightningModule]AutoBotEgo.on_train_epoch_start                                                                                                                             |  8.7638e-07             |  100                  |  8.7638e-05           |  2.3784e-05           |
|  [LightningModule]AutoBotEgo.on_validation_batch_end                                                                                                                          |  8.4741e-07             |  101                  |  8.5589e-05           |  2.3227e-05           |
|  [LightningModule]AutoBotEgo.on_validation_epoch_start                                                                                                                        |  7.9478e-07             |  101                  |  8.0273e-05           |  2.1785e-05           |
|  [Strategy]SingleDeviceStrategy.on_validation_start                                                                                                                           |  7.7752e-07             |  101                  |  7.853e-05            |  2.1312e-05           |
|  [Callback]ModelCheckpoint{'monitor': 'val/brier_fde', 'mode': 'min', 'every_n_train_steps': 0, 'every_n_epochs': 1, 'train_time_interval': None}.on_validation_batch_start   |  7.7506e-07             |  101                  |  7.8281e-05           |  2.1244e-05           |
|  [LightningModule]AutoBotEgo.on_validation_batch_start                                                                                                                        |  7.6363e-07             |  101                  |  7.7127e-05           |  2.0931e-05           |
|  [Callback]ModelSummary.on_validation_epoch_start                                                                                                                             |  7.4841e-07             |  101                  |  7.5589e-05           |  2.0514e-05           |
|  [LightningModule]AutoBotEgo.on_validation_end                                                                                                                                |  7.1478e-07             |  101                  |  7.2193e-05           |  1.9592e-05           |
|  [Strategy]SingleDeviceStrategy.on_validation_end                                                                                                                             |  6.9492e-07             |  101                  |  7.0187e-05           |  1.9048e-05           |
|  [Callback]ModelCheckpoint{'monitor': 'val/brier_fde', 'mode': 'min', 'every_n_train_steps': 0, 'every_n_epochs': 1, 'train_time_interval': None}.on_validation_batch_end     |  6.7706e-07             |  101                  |  6.8383e-05           |  1.8558e-05           |
|  [LightningModule]AutoBotEgo.on_train_epoch_end                                                                                                                               |  6.6111e-07             |  100                  |  6.6111e-05           |  1.7941e-05           |
|  [Callback]ModelCheckpoint{'monitor': 'val/brier_fde', 'mode': 'min', 'every_n_train_steps': 0, 'every_n_epochs': 1, 'train_time_interval': None}.on_train_epoch_start        |  5.6061e-07             |  100                  |  5.6061e-05           |  1.5214e-05           |
|  [Callback]ModelSummary.on_validation_epoch_end                                                                                                                               |  5.4093e-07             |  101                  |  5.4634e-05           |  1.4827e-05           |
|  [Callback]ModelCheckpoint{'monitor': 'val/brier_fde', 'mode': 'min', 'every_n_train_steps': 0, 'every_n_epochs': 1, 'train_time_interval': None}.on_validation_epoch_end     |  4.9327e-07             |  101                  |  4.982e-05            |  1.352e-05            |
|  [Callback]TQDMProgressBar.on_save_checkpoint                                                                                                                                 |  1.3236e-06             |  36                   |  4.7649e-05           |  1.2931e-05           |
|  [Callback]ModelSummary.setup                                                                                                                                                 |  2.4742e-05             |  1                    |  2.4742e-05           |  6.7146e-06           |
|  [Callback]ModelCheckpoint{'monitor': 'val/brier_fde', 'mode': 'min', 'every_n_train_steps': 0, 'every_n_epochs': 1, 'train_time_interval': None}.setup                       |  2.3103e-05             |  1                    |  2.3103e-05           |  6.2698e-06           |
|  [Callback]ModelSummary.on_save_checkpoint                                                                                                                                    |  5.2533e-07             |  36                   |  1.8912e-05           |  5.1324e-06           |
|  [Callback]ModelCheckpoint{'monitor': 'val/brier_fde', 'mode': 'min', 'every_n_train_steps': 0, 'every_n_epochs': 1, 'train_time_interval': None}.on_save_checkpoint          |  4.5985e-07             |  36                   |  1.6555e-05           |  4.4927e-06           |
|  [LightningModule]AutoBotEgo.on_save_checkpoint                                                                                                                               |  4.0366e-07             |  36                   |  1.4532e-05           |  3.9437e-06           |
|  [Callback]TQDMProgressBar.setup                                                                                                                                              |  3.465e-06              |  1                    |  3.465e-06            |  9.4034e-07           |
|  [Callback]TQDMProgressBar.on_fit_start                                                                                                                                       |  2.3609e-06             |  1                    |  2.3609e-06           |  6.4071e-07           |
|  [Callback]TQDMProgressBar.on_sanity_check_end                                                                                                                                |  2.2869e-06             |  1                    |  2.2869e-06           |  6.2062e-07           |
|  [LightningModule]AutoBotEgo.configure_callbacks                                                                                                                              |  1.8538e-06             |  1                    |  1.8538e-06           |  5.0309e-07           |
|  [Callback]ModelSummary.on_sanity_check_start                                                                                                                                 |  1.7162e-06             |  1                    |  1.7162e-06           |  4.6575e-07           |
|  [Callback]TQDMProgressBar.on_fit_end                                                                                                                                         |  1.495e-06              |  1                    |  1.495e-06            |  4.0572e-07           |
|  [LightningModule]AutoBotEgo.setup                                                                                                                                            |  1.2529e-06             |  1                    |  1.2529e-06           |  3.4001e-07           |
|  [Callback]ModelCheckpoint{'monitor': 'val/brier_fde', 'mode': 'min', 'every_n_train_steps': 0, 'every_n_epochs': 1, 'train_time_interval': None}.on_fit_start                |  1.227e-06              |  1                    |  1.227e-06            |  3.3299e-07           |
|  [Callback]ModelSummary.on_train_end                                                                                                                                          |  1.2261e-06             |  1                    |  1.2261e-06           |  3.3274e-07           |
|  [Callback]ModelSummary.on_train_start                                                                                                                                        |  1.1381e-06             |  1                    |  1.1381e-06           |  3.0886e-07           |
|  [LightningModule]AutoBotEgo.on_fit_start                                                                                                                                     |  1.126e-06              |  1                    |  1.126e-06            |  3.0557e-07           |
|  [Callback]ModelCheckpoint{'monitor': 'val/brier_fde', 'mode': 'min', 'every_n_train_steps': 0, 'every_n_epochs': 1, 'train_time_interval': None}.on_train_start              |  1.0349e-06             |  1                    |  1.0349e-06           |  2.8086e-07           |
|  [Callback]TQDMProgressBar.teardown                                                                                                                                           |  9.3505e-07             |  1                    |  9.3505e-07           |  2.5376e-07           |
|  [LightningModule]AutoBotEgo.teardown                                                                                                                                         |  8.1118e-07             |  1                    |  8.1118e-07           |  2.2014e-07           |
|  [Callback]ModelSummary.teardown                                                                                                                                              |  7.0105e-07             |  1                    |  7.0105e-07           |  1.9025e-07           |
|  [Callback]ModelCheckpoint{'monitor': 'val/brier_fde', 'mode': 'min', 'every_n_train_steps': 0, 'every_n_epochs': 1, 'train_time_interval': None}.on_sanity_check_start       |  6.8592e-07             |  1                    |  6.8592e-07           |  1.8615e-07           |
|  [LightningModule]AutoBotEgo.on_train_end                                                                                                                                     |  6.7102e-07             |  1                    |  6.7102e-07           |  1.821e-07            |
|  [Callback]ModelSummary.on_sanity_check_end                                                                                                                                   |  6.6403e-07             |  1                    |  6.6403e-07           |  1.8021e-07           |
|  [Callback]ModelCheckpoint{'monitor': 'val/brier_fde', 'mode': 'min', 'every_n_train_steps': 0, 'every_n_epochs': 1, 'train_time_interval': None}.on_train_end                |  6.4797e-07             |  1                    |  6.4797e-07           |  1.7585e-07           |
|  [LightningModule]AutoBotEgo.on_fit_end                                                                                                                                       |  6.34e-07               |  1                    |  6.34e-07             |  1.7206e-07           |
|  [LightningModule]AutoBotEgo.on_train_start                                                                                                                                   |  6.3214e-07             |  1                    |  6.3214e-07           |  1.7155e-07           |
|  [Callback]ModelCheckpoint{'monitor': 'val/brier_fde', 'mode': 'min', 'every_n_train_steps': 0, 'every_n_epochs': 1, 'train_time_interval': None}.on_fit_end                  |  6.2701e-07             |  1                    |  6.2701e-07           |  1.7016e-07           |
|  [Callback]ModelCheckpoint{'monitor': 'val/brier_fde', 'mode': 'min', 'every_n_train_steps': 0, 'every_n_epochs': 1, 'train_time_interval': None}.on_sanity_check_end         |  6.0815e-07             |  1                    |  6.0815e-07           |  1.6504e-07           |
|  [Callback]ModelSummary.on_fit_end                                                                                                                                            |  5.5996e-07             |  1                    |  5.5996e-07           |  1.5196e-07           |
|  [Callback]ModelCheckpoint{'monitor': 'val/brier_fde', 'mode': 'min', 'every_n_train_steps': 0, 'every_n_epochs': 1, 'train_time_interval': None}.teardown                    |  5.581e-07              |  1                    |  5.581e-07            |  1.5146e-07           |
|  [Strategy]SingleDeviceStrategy.on_train_start                                                                                                                                |  5.5507e-07             |  1                    |  5.5507e-07           |  1.5064e-07           |
|  [Strategy]SingleDeviceStrategy.on_train_end                                                                                                                                  |  4.7707e-07             |  1                    |  4.7707e-07           |  1.2947e-07           |
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Even though there's output, there are still errors being thrown. What's the potential issue here? Do I need to worry about it?
Thanks for answering my questions.

**Comment by Alan-LanFeng** [comment]
I think these are just warnings which you don't need to worry about.
