### ISSUE TITLE
Questions about training details

### ISSUE THREAD

**Issue by ChengkaiYang** [vita-epfl/UniTraj#3]
Dear author:
       Sorry to disturb you. You have show me the new link of your work. In your paper, you evaluate the result on Nuscenes of the model trained on the Nuscenes dataset--"3.36" for brier-minFDE in the following picture. Is the evaluation dataset same as training dataset? To solve my confusion, I have checked the config file in your project.I saw the parameters "train_data_path" and "val_data_path" are the same, set "data_samples/nuscenes".I want to ask if it is correct?Thanks!

<img width="1061" alt="image" src="https://github.com/vita-epfl/UniTraj/assets/71952712/18bd548f-18a5-4d41-aae7-57f9528c36f2">

**Comment by ChengkaiYang** [comment]
Did your team split the nuscenes dataset into training set and evaluation set OR training set and evaluation set are the same?

**Comment by Alan-LanFeng** [comment]
We split all the datasets into training and validation corresponding to their official split
