### ISSUE TITLE
time_onehot

### ISSUE THREAD

**Issue by AntoineTF** [vita-epfl/UniTraj#31]
Hello,
First, thank you for the incredible work on UniTraj! It’s a fantastic project, and I’ve found it very useful for my work.

I’ve generated a dataset of simulations using the convert_pg.py function from the scenarionet module, and I have a few questions regarding the preprocessing steps before passing the dataset to UniTraj.

- Time_onehot Embedding: The trajectories in my dataset have varying lengths (i.e., different sizes for the position vectors). From what I understand, UniTraj processes trajectories using a fixed time window (e.g., 6 seconds). Do I need to manually crop or select specific time intervals for each trajectory, or can I pass my dataset as it is? Specifically, will UniTraj automatically crop the trajectories in terms of time if they are too long?

- Train/Test Split: Should I provide separate train and test sets myself, or does UniTraj handle this splitting internally during data processing?

Thank you again for the amazing work and for any insights you can provide!

**Comment by Alan-LanFeng** [comment]
Hello,

1. Yes. UniTraj will crop the trajectories to make sure they have the same length.
2. You need to define training and validation dataset path in config.yaml. UniTraj will train on the data listed in the training path.

**Comment by AntoineTF** [comment]
Hello,

Thank you for your answer!

Following up on your explanation about UniTraj cropping the trajectories, I was trying to find the relevant part in the code but couldn’t locate it. Could you clarify if it simply takes the first X elements of each trajectory, or does it crop based on a different logic?

Thanks again for your help!
