### ISSUE TITLE
Question about MTR model

### ISSUE THREAD

**Issue by Keirra0116** [vita-epfl/UniTraj#33]
Thanks for your excellent work!
I am working on reproducing the results of your MTR model on the nuScenes dataset. While I managed to achieve results similar to those reported in the paper when reproducing Autobot, the MTR model's performance has been significantly worse than expected. All the parameters used were kept at their default values as per the codebase, and no additional modifications were made.
Do I need to further adjust the MTR parameters for better performance on nuScenes, or is there any recommended configuration?

Thank you!

**Comment by Alan-LanFeng** [comment]
Hi, can you show me the config file you are using? thanks

**Comment by Keirra0116** [comment]
Thank you for your quick response!

Below are the specific configurations I used in MTR.yaml and config.yaml:
### MTR.yaml
```# common
model_name: MTR

# model
CONTEXT_ENCODER:
  NAME: MTREncoder
  NUM_OF_ATTN_NEIGHBORS: 7
  NUM_INPUT_ATTR_AGENT: 39
  NUM_INPUT_ATTR_MAP: 29
  NUM_CHANNEL_IN_MLP_AGENT: 256
  NUM_CHANNEL_IN_MLP_MAP: 64
  NUM_LAYER_IN_MLP_AGENT: 3
  NUM_LAYER_IN_MLP_MAP: 5
  NUM_LAYER_IN_PRE_MLP_MAP: 3
  D_MODEL: 256
  NUM_ATTN_LAYERS: 6
  NUM_ATTN_HEAD: 8
  DROPOUT_OF_ATTN: 0.1
  USE_LOCAL_ATTN: True

MOTION_DECODER:
  NAME: MTRDecoder
  NUM_MOTION_MODES: 6
  INTENTION_POINTS_FILE: 'models/mtr/cluster_64_center_dict_6s.pkl'
  D_MODEL: 512
  NUM_DECODER_LAYERS: 6
  NUM_ATTN_HEAD: 8
  MAP_D_MODEL: 256
  DROPOUT_OF_ATTN: 0.1
  NUM_BASE_MAP_POLYLINES: 256
  NUM_WAYPOINT_MAP_POLYLINES: 128
  LOSS_WEIGHTS: {
    'cls': 1.0,
    'reg': 1.0,
    'vel': 0.5
  }

  NMS_DIST_THRESH: 2.5

# train
max_epochs: 40
learning_rate: 0.0001
learning_rate_sched: [ 22, 24, 26, 28 ]
optimizer: AdamW
scheduler: lambdaLR
grad_clip_norm: 1000.0
weight_decay: 0.01
lr_decay: 0.5
lr_clip: 0.000001
WEIGHT_DECAY: 0.01
train_batch_size: 256
eval_batch_size: 512

# data related
max_num_agents: 64
map_range: 100
max_num_roads: 768

max_points_per_lane: 20

manually_split_lane: True
point_sampled_interval: 1
num_points_each_polyline: 20
vector_break_dist_thresh: 1.0
```
### config.yaml
```
# exp setting
exp_name: 'MTR_nuscenes' # name that will be used in wandb
ckpt_path: null # checkpoint path, used for evaluation
seed: 42 # random seed
debug: False # debug mode, will use cpu only
devices: [ 0,1,2,3,4,5,6,7 ] # gpu ids

# data related
load_num_workers: 0 # number of workers for loading data
train_data_path: [ "/data/quanxy/project_new/DATASET/nuscenes_processed/trainval" ] # list of paths to the training data
val_data_path: [ "/data/quanxy/project_new/DATASET/nuscenes_processed/test" ] # list of paths to the validation data
max_data_num: [ 1000 ] 
starting_frame: [ 0 ] # history trajectory starts at this frame for each training dataset
past_len: 21 # history trajectory length, 2.1s
future_len: 60 # future trajectory length, 6s
object_type: [ 'VEHICLE' ]#, 'PEDESTRIAN', 'CYCLIST'] # object types included in the training set
line_type: [ 'lane','stop_sign','road_edge','road_line','crosswalk','speed_bump' ] # line type to be considered in the input
masked_attributes: [ 'z_axis', 'size' ] # attributes to be masked in the input
trajectory_sample_interval: 1 # sample interval for the trajectory
only_train_on_ego: False # only train on AV
center_offset_of_map: [ 30.0, 0.0 ] # center offset of the map
use_cache: False # use cache for data loading
overwrite_cache: True # overwrite existing cache
store_data_in_memory: False # store data in memory

# official evaluation
nuscenes_dataroot: '/mnt/nas3_rcp_enac_u0900_vita_scratch/datasets/Prediction-Dataset/nuscenes/nuscenes_root'
eval_nuscenes: False # whether to evaluate with nuscenes evaluation tool
eval_waymo: False # whether to evaluate with waymo evaluation tool

defaults:
  - method: MTR
```

For dataset processing, I followed the steps outlined in the [ScenarioNet documentation for nuScenes](https://scenarionet.readthedocs.io/en/latest/nuscenes.html).

Thank you again!

**Comment by Alan-LanFeng** [comment]
Hi,

max_data_num: [ 1000 ] 
Here you need to set max_data_num to -1 to use all the data in nuscenes. There should be around 32k training samples in nuscenes.

**Comment by Keirra0116** [comment]
Hi,

Thank you for the suggestion! I set max_data_num to -1 as you recommended to use the full nuScenes dataset. However, I noticed that the output only shows "Loaded 2040 samples" eight times, totaling around 16,320 samples, rather than the expected ~32k training samples.

I went ahead and trained the MTR model using these ~16k samples, but the results are still not ideal. 

Would the limited dataset size likely affect this, or are there any additional adjustments you’d recommend?

Thanks again for your guidance!

**Comment by Keirra0116** [comment]
I checked previous issues and realized the problem was due to an incorrect splits setting when generating the dataset. I was using the wrong split configuration, which led to only partial data being loaded.

Thanks for pointing me in the right direction!
