### ISSUE TITLE
Question about Autobot model

### ISSUE THREAD

**Issue by Karim-SUN** [vita-epfl/UniTraj#36]
Hi, team of UniTraj.

I've noticed that the Autobot implementation here takes only the ego-agent encodings from all `agents_emb`, which is then used as context in `tx_decoder`. And in `map_encoder`, model's decoding layer and mode prediction all the information about agent's states and historical trajectories are ignored while merely considering ego-agent embeddings after temporal and social attention blocks. 

I wonder why the surrounding agents' features are discarded in Autobot and what would the model benefit from such designs. Will the model achieve higher performances when it attends to the whole `agents_emb`? Or did I miss some details in the code that brought me to the wrong conclusion.

Looking forward to your precious reply :)

**Comment by Alan-LanFeng** [comment]
Hi, since I'm not in charge of the implementation of AutoBot, I'm not quite sure about your question.

My understanding is, Autobot has two training schemes, 1: single agent and 2. multi agent. We are using the single agent version.

**Comment by Karim-SUN** [comment]
Ok, thx for the response.
