### ISSUE TITLE
Question about Environment 

### ISSUE THREAD

**Issue by jayahn77777** [vita-epfl/UniTraj#39]
I am currently setup with following environment:

- ubuntu 22.04 LTS
- Python 3.10
- Cuda Version : 11.8

Your documentation(scenarionet) recommends using  Python 3.8 and 3.9, but does this mean Python 3.10 is not supported?

Do you have any plans to make Python 3.10 compatible in the future?

**Comment by Alan-LanFeng** [comment]
We have tested python 3.11 and it works well. So 3.10 is supposed to be compatible. Feel free to raise an issue if something goes wrong.
