### ISSUE TITLE
FileNotFoundError : Checkpoint path issue

### ISSUE THREAD

**Issue by jayahn77777** [vita-epfl/UniTraj#41]
Currently, I have set up the environment using Ubuntu 20.04, Python 3.8, and CUDA 11.8.
I ran the sample code you provided, python train.py method=autobot.

As a result, a folder named Unitraj/unitraj/unitraj_ckpt was created, and within it, several folders were generated: a test folder, and folders named epoch=0-val through epoch=98-val. In the epoch=98-val folder, I confirmed that a file named brier_fde=9.44.ckpt was created.

After that, when I ran python evaluation, the following error occurred:
FileNotFoundError: Checkpoint file not found ['unitraj_ckpt/test/epoch=98-val/brier_fed=9.44-v1.ckpt']

In the config.yaml file, I tried setting the ckpt_path: null field to each of the following three paths, but I still received the same FileNotFoundError: Checkpoint file not found error:

"unitraj_ckpt/test/epoch=98-val/brier_fed=9.44-v1.ckpt"
"unitraj_ckpt/test/epoch=98-val"
"unitraj_ckpt/test"
How can I resolve this issue?

**Comment by jayahn77777** [comment]
Thank you for answering my question.

Even though I tried the first path(ckpt_path) with the absolute path, I still received the same error.

FileNotFoundError: Checkpoint file not found: ['D:/Coding/Python/nuScenes/unitraj/UniTraj/unitraj/unitraj_ckpt/test/epoch=99-val']

FileNotFoundError: Checkpoint file not found: ['D:/Coding/Python/nuScenes/unitraj/UniTraj/unitraj/unitraj_ckpt/test/epoch=99-val/brier_fde=9.42.ckpt']

**Comment by Alan-LanFeng** [comment]
Can you try to remove '[]'

**Comment by jayahn77777** [comment]
Thank you for answer

Finally, I got below results. (I used only mini data. That's why I got ugly results.)

(unitraj) D:\Coding\Python\nuScenes\unitraj\UniTraj\unitraj>python evaluation.py
C:\Users\xxxx\.conda\envs\unitraj\lib\site-packages\hydra\_internal\defaults_list.py:251: UserWarning: In 'config': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
Seed set to 42
C:\Users\xxxx\.conda\envs\unitraj\lib\site-packages\torch\nn\modules\transformer.py:307: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(f"enable_nested_tensor is True, but self.use_nested_tensor is False because {why_not_sparsity_fast_path}")
Loading validation data...
Warning: cache path ./cache\nuscenes\data_samples already exists, skip 
Loaded 61 samples from data_samples/nuscenes
Data loaded
GPU available: True (cuda), used: False
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
C:\Users\ahn_j\.conda\envs\unitraj\lib\site-packages\pytorch_lightning\trainer\setup.py:177: GPU available but not used. You can set it by doing `Trainer(accelerator='gpu')`.
Restoring states from the checkpoint path at D:/Coding/Python/nuScenes/unitraj/UniTraj/unitraj/unitraj_ckpt/test/epoch=99-val/brier_fde=9.42.ckpt
Loaded model weights from the checkpoint at D:/Coding/Python/nuScenes/unitraj/UniTraj/unitraj/unitraj_ckpt/test/epoch=99-val/brier_fde=9.42.ckpt
C:\Users\ahn_j\.conda\envs\unitraj\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:424: The 'val_dataloader' does not have many workers 
which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=23` in the `DataLoader` to improve performance.
Validation DataLoader 0: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.01it/s] 
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃            Validate metric             ┃              DataLoader 0              ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│   val/agent_types/vehicle_brier_fde    │           9.421167373657227            │
│    val/agent_types/vehicle_minADE6     │           4.392564296722412            │
│    val/agent_types/vehicle_minFDE6     │           8.726568222045898            │
│   val/agent_types/vehicle_miss_rate    │           0.7704917788505554           │
│             val/brier_fde              │           9.421167373657227            │
│       val/kalman/easy_brier_fde        │           9.421167373657227            │
│        val/kalman/easy_minADE6         │           4.392564296722412            │
│        val/kalman/easy_minFDE6         │           8.726568222045898            │
│       val/kalman/easy_miss_rate        │           0.7704917788505554           │
│              val/minADE6               │           4.392564296722412            │
│              val/minFDE6               │           8.726568222045898            │
│             val/miss_rate              │           0.7704917788505554           │
│         val/nuscenes/brier_fde         │           9.421167373657227            │
│          val/nuscenes/minADE6          │           4.392564296722412            │
│          val/nuscenes/minFDE6          │           8.726568222045898            │
│         val/nuscenes/miss_rate         │           0.7704917788505554           │
│   val/traj_type/left_turn_brier_fde    │           14.89672565460205            │
│    val/traj_type/left_turn_minADE6     │           4.827913284301758            │
│    val/traj_type/left_turn_minFDE6     │           14.201919555664062           │
│   val/traj_type/left_turn_miss_rate    │           0.8999999761581421           │
│   val/traj_type/right_turn_brier_fde   │           8.442954063415527            │
│    val/traj_type/right_turn_minADE6    │           4.928262710571289            │
│    val/traj_type/right_turn_minFDE6    │           7.748167991638184            │
│   val/traj_type/right_turn_miss_rate   │           0.7222222089767456           │
│   val/traj_type/stationary_brier_fde   │            2.76753306388855            │
│    val/traj_type/stationary_minADE6    │           1.3035895824432373           │
│    val/traj_type/stationary_minFDE6    │           2.0737736225128174           │
│   val/traj_type/stationary_miss_rate   │                  0.5                   │
│    val/traj_type/straight_brier_fde    │           13.357741355895996           │
│     val/traj_type/straight_minADE6     │           6.119167327880859            │
│     val/traj_type/straight_minFDE6     │           12.662769317626953           │
│    val/traj_type/straight_miss_rate    │           0.9411764740943909           │
│ val/traj_type/straight_right_brier_fde │           3.9618747234344482           │
│  val/traj_type/straight_right_minADE6  │           4.341213226318359            │
│  val/traj_type/straight_right_minFDE6  │           3.2672505378723145           │
│ val/traj_type/straight_right_miss_rate │                  1.0                   │
└────────────────────────────────────────┴────────────────────────────────────────┘
VALIDATE Profiler Report

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|  Action
        |  Mean duration (s)    |  Num calls            |  Total time (s)       |  Percentage %         |
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|  Total
        |  -                    |  43                   |  1.625                |  100 %                |
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|  [Strategy]SingleDeviceStrategy.validation_step
        |  0.969                |  1                    |  0.969                |  59.631               |
|  [_EvaluationLoop].val_next
        |  0.453                |  1                    |  0.453                |  27.877               |
|  [LightningModule]AutoBotEgo.configure_callbacks
        |  0.0                  |  1                    |  0.0                  |  0.0                  |
|  [Callback]TQDMProgressBar.setup
        |  0.0                  |  1                    |  0.0                  |  0.0                  |
|  [Callback]ModelSummary.setup
        |  0.0                  |  1                    |  0.0                  |  0.0                  |
|  [Callback]ModelCheckpoint{'monitor': None, 'mode': 'min', 'every_n_train_steps': 0, 'every_n_epochs': 1, 'train_time_interval': None}.setup
        |  0.0                  |  1                    |  0.0                  |  0.0                  |
|  [LightningModule]AutoBotEgo.setup
        |  0.0                  |  1                    |  0.0                  |  0.0                  |
|  [LightningModule]AutoBotEgo.on_load_checkpoint
        |  0.0                  |  1                    |  0.0                  |  0.0                  |
|  [LightningModule]AutoBotEgo.on_validation_model_eval
        |  0.0                  |  1                    |  0.0                  |  0.0                  |
|  [Callback]TQDMProgressBar.on_validation_start
        |  0.0                  |  1                    |  0.0                  |  0.0                  |
|  [Callback]ModelSummary.on_validation_start
        |  0.0                  |  1                    |  0.0                  |  0.0                  |
|  [Callback]ModelCheckpoint{'monitor': None, 'mode': 'min', 'every_n_train_steps': 0, 'every_n_epochs': 1, 'train_time_interval': None}.on_validation_start     
        |  0.0                  |  1                    |  0.0                  |  0.0                  |
|  [LightningModule]AutoBotEgo.on_validation_start
        |  0.0                  |  1                    |  0.0                  |  0.0                  |
|  [Strategy]SingleDeviceStrategy.on_validation_start
        |  0.0                  |  1                    |  0.0                  |  0.0                  |
|  [Callback]TQDMProgressBar.on_validation_epoch_start
        |  0.0                  |  1                    |  0.0                  |  0.0                  |
|  [Callback]ModelSummary.on_validation_epoch_start
        |  0.0                  |  1                    |  0.0                  |  0.0                  |
|  [Callback]ModelCheckpoint{'monitor': None, 'mode': 'min', 'every_n_train_steps': 0, 'every_n_epochs': 1, 'train_time_interval': None}.on_validation_epoch_start       |  0.0                  |  1                    |  0.0                  |  0.0                  |
|  [LightningModule]AutoBotEgo.on_validation_epoch_start
        |  0.0                  |  1                    |  0.0                  |  0.0                  |
|  [LightningModule]AutoBotEgo.on_before_batch_transfer
        |  0.0                  |  1                    |  0.0                  |  0.0                  |
|  [LightningModule]AutoBotEgo.transfer_batch_to_device
        |  0.0                  |  1                    |  0.0                  |  0.0                  |
|  [LightningModule]AutoBotEgo.on_after_batch_transfer
        |  0.0                  |  1                    |  0.0                  |  0.0                  |
|  [Strategy]SingleDeviceStrategy.batch_to_device
        |  0.0                  |  1                    |  0.0                  |  0.0                  |
|  [Callback]TQDMProgressBar.on_validation_batch_start
        |  0.0                  |  1                    |  0.0                  |  0.0                  |
|  [Callback]ModelSummary.on_validation_batch_start
        |  0.0                  |  1                    |  0.0                  |  0.0                  |
|  [Callback]ModelCheckpoint{'monitor': None, 'mode': 'min', 'every_n_train_steps': 0, 'every_n_epochs': 1, 'train_time_interval': None}.on_validation_batch_start       |  0.0                  |  1                    |  0.0                  |  0.0                  |
|  [LightningModule]AutoBotEgo.on_validation_batch_start
        |  0.0                  |  1                    |  0.0                  |  0.0                  |
|  [Callback]TQDMProgressBar.on_validation_batch_end
        |  0.0                  |  1                    |  0.0                  |  0.0                  |
|  [Callback]ModelSummary.on_validation_batch_end
        |  0.0                  |  1                    |  0.0                  |  0.0                  |
|  [Callback]ModelCheckpoint{'monitor': None, 'mode': 'min', 'every_n_train_steps': 0, 'every_n_epochs': 1, 'train_time_interval': None}.on_validation_batch_end 
        |  0.0                  |  1                    |  0.0                  |  0.0                  |
|  [LightningModule]AutoBotEgo.on_validation_batch_end
        |  0.0                  |  1                    |  0.0                  |  0.0                  |
|  [Callback]TQDMProgressBar.on_validation_epoch_end
        |  0.0                  |  1                    |  0.0                  |  0.0                  |
|  [Callback]ModelSummary.on_validation_epoch_end
        |  0.0                  |  1                    |  0.0                  |  0.0                  |
|  [Callback]ModelCheckpoint{'monitor': None, 'mode': 'min', 'every_n_train_steps': 0, 'every_n_epochs': 1, 'train_time_interval': None}.on_validation_epoch_end 
        |  0.0                  |  1                    |  0.0                  |  0.0                  |
|  [LightningModule]AutoBotEgo.on_validation_epoch_end
        |  0.0                  |  1                    |  0.0                  |  0.0                  |
|  [Callback]TQDMProgressBar.on_validation_end
        |  0.0                  |  1                    |  0.0                  |  0.0                  |
|  [Callback]ModelSummary.on_validation_end
        |  0.0                  |  1                    |  0.0                  |  0.0                  |
|  [Callback]ModelCheckpoint{'monitor': None, 'mode': 'min', 'every_n_train_steps': 0, 'every_n_epochs': 1, 'train_time_interval': None}.on_validation_end       
        |  0.0                  |  1                    |  0.0                  |  0.0                  |
    |  0.0                  |  1                    |  0.0                  |  0.0                  |
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
