### ISSUE TITLE
Waymo Dataset Training Issue & Model Checkpoint

### ISSUE THREAD

**Issue by RobertRen1122** [vita-epfl/UniTraj#5]
Hi,

Thank you for the amazing work! I have a question regarding training a trajectory prediction model using the waymo dataset. I followed the steps [here](https://scenarionet.readthedocs.io/en/latest/example.html) to download the dataset and ran `python -m scenarionet.convert_waymo -d UniTraj/unitraj/data_samples/waymo --raw_data_path ../dataset/waymo/training_20s/ --num_workers 64`. Below is the result after the data processing code is finished.
```================ Dataset Summary and Mapping are saved at: UniTraj/unitraj/data_samples/waymo/waymo_63_tmp/dataset_summary.pkl ================
INFO:scenarionet/scenarionet/converter/utils.py:Worker 63 finished! Files are saved at: UniTraj/unitraj/data_samples/waymo/waymo_63
Merge Data: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:03<00:00, 16.60it/s]
Filter Scenarios: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 70541/70541 [00:00<00:00, 2440651.33it/s]
INFO:root:
 ================ Dataset Summary and Mapping are saved at: UniTraj/unitraj/data_samples/waymo/dataset_summary.pkl ================
```
Now that the processed waymo dataset has a the same structure as the `nuscenes` folder under the `data_samples` folder.  However, when I run `python train.py` (after changing the dataset path in `configs/config.yaml`), I get the following error and warning for every file in the waymo folder:
```Warning: no center objects at time step 20, scene_id=470050f61839dd13
Error: 'NoneType' object is not iterable in sd_waymo_v1.2_470050f61839dd13.pkl
Warning: no center objects at time step 20, scene_id=c9281284c99138ef
Error: 'NoneType' object is not iterable in sd_waymo_v1.2_c9281284c99138ef.pkl
```
which means that we are not getting any training trajectories. I was wondering if I have missed any steps to run training on the waymo dataset. Any help is appreaciated, thank you!

Also, are there any plans to release some model checkpoints soon?

**Comment by Alan-LanFeng** [comment]
Hi, the error shows that you have successfully processed the data with scenarionet. It's normal that for some scenarios there are no training trajectories. However, if you are not getting any samples from all the scenarios, you can try to remove all the 'try except' in the base_dataset.py to locate the bug. Please keep me updated if this is a bug. Thanks

**Comment by Alan-LanFeng** [comment]
Also, we are planning to release some checkpoints when we have a stable version of the code.

**Comment by RobertRen1122** [comment]
Hi Alan, thank you very much for the quick reply! I will look more into the waymo data processing code and post here if I have an update.

**Comment by RobertRen1122** [comment]
I have figured out the issue. For my case, the data in `training_20s` folder didn't have any values for the field`tracks_to_predict`. Only the data in `training` folder have values for the field `tracks_to_predict`.
