### ISSUE TITLE
About nuScenes training

### ISSUE THREAD

**Issue by KeiMichael** [vita-epfl/UniTraj#9]
Dear Author :
Thank you for the great research.
I am using the nuScenes dataset (v1.0-trainval) to train Wayformer.
I have two questions regarding this.

1. My purpose is to replicate the experiment in the UniTraj paper using the nuScenes dataset (v1.0-trainval). First, I converted nuScenes v1.0-trainval into pkl files using `scenarionet/convert_nuscenes.py` and then used `scenarionet/split.py` to split all 850 scenes into 700 scenes of a train dataset and 150 scenes of a validation dataset. The train dataset and validation dataset were used to train Wayformer, and the birer-minFDE for the validation data was 7.98, which is higher than the value reported in the UniTraj paper. The config file is the one on github, except I changed the path to the dataset. If you don't mind, I would like to know how you created the correct data from the nuScenes dataset you used in your paper and the hyperparameter settings.<br><br>

2. I want to create a dataset like the one placed in the 'data_samples' directory. There were two differences between the pkl files I created from the nuScenes dataset using scenarionet/convert_nuscenes.py and the dataset placed in the 'data_samples' directory in your repository. The first difference is the pkl file name. The name of the pkl file I created turned out to be something like 'sd_nuscenes_v1.0-trainval_scene-0001.pkl', while the name of the pkl file placed in the 'data_samples' directory have the instance token or sample token after the scene number. The second difference is the presence of the 'tracks_to_predict' key. The data in the pkl files I created does not have the 'tracks_to_predict' key, while the data in the pkl files located in the 'data_samples' directory has the 'tracks_to_predict' key. Please tell me what causes these two differences and how to deal with them. When creating the pkl files with ScenarioNet, I followed the commands according to the official website ( https://scenarionet.readthedocs.io/en/latest/nuscenes.html#build-nuscenes-database ). <br><br>
Sorry for my poor English. Please give me your answer.

**Comment by Alan-LanFeng** [comment]
1. We trained wayformer with the whole nuscenes training set without splitting it. Also there's small bug in wayformer which has been fixed in the latest commit. Please update your repo first.

2. When using scenarionet,  set --split to the following options: prediction_split = ["mini_train", "mini_val", "train", "train_val", "val"]

**Comment by KeiMichael** [comment]
Thank you for your quick response. I will try the method you gave me.

**Comment by iyuner** [comment]
Hi @Alan-LanFeng , Thank you for the great work and share! For the first reply regarding not splitting the training set, do you mean that you used all 700 scenes for training by changing `NUM_IN_TRAIN_VAL` [here](https://github.com/nutonomy/nuscenes-devkit/blob/835ddecae31c763bcb303a16cc715df77d77c1a3/python-sdk/nuscenes/eval/prediction/splits.py#L11C1-L11C17)? If I understand correctly, for the prediction, the default nuScenes not used all 700 scenes for training, but 500? Could you elaborate more about your training and validation data?

> 1. We trained wayformer with the whole nuscenes training set without splitting it. Also there's small bug in wayformer which has been fixed in the latest commit. Please update your repo first.
> 2. When using scenarionet,  set --split to the following options: prediction_split = ["mini_train", "mini_val", "train", "train_val", "val"]

**Comment by Alan-LanFeng** [comment]
Hi, thanks for asking.

We are using the 'train' split in nuscenes, which contains 500 scenes. The model is evaluated on the 'val' split.

This means that we have not touched the 'train_val' split. So it is expected that using the rest 200 scenes will further improve performance.

**Comment by iyuner** [comment]
I see, thanks for your reply!
